DISPLAY_ROOT := $(abs_srctree)/techpack/display

CAMERA_KERNEL_ROOT := $(abs_srctree)/techpack/camera-kernel
CAMERA_ARCH := qcm6490
KERNEL_ROOT := $(abs_srctree)
KERNEL_SRC  := $(abs_srctree)
MACHINE := qcm6490

export DISPLAY_ROOT
export CAMERA_KERNEL_ROOT
export CAMERA_ARCH
export KERNEL_ROOT
export MACHINE

obj-y += display/
obj-y += camera-kernel/
